<a href="https://colab.research.google.com/github/UktamSam/AI_Foundation/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np

arr = np.array([1, 3, 5, 7])
print('numpy_array:', arr)

arr.shape

numpy_array: [1 3 5 7]


(4,)

In [ ]:
arr2 = np.array([[1, 3, 5, 7], [4, 3, 5, 9]])
print('numpy_array2:', arr2)

arr2.shape

numpy_array2: [[1 3 5 7]
 [4 3 5 9]]


(2, 4)

In [ ]:
#dtype
a = np.array([1, 2, 3])
print(a.dtype)

int64


In [ ]:
# reshape ()
a = np.array([1, 2, 3, 4, 6, 7])
b = a.reshape(2,3)
print('shaped_array:', b)

shaped_array: [[1 2 3]
 [4 6 7]]
int64


In [ ]:
# astype()
a = np.array([1, 2, 3])
b = a.astype(float)
print('float:', b)

float: [1. 2. 3.]


In [8]:
# np.zeros(), np.ones() => dummy data
import numpy as np
z = np.zeros((2, 3))
o = np.ones((2, 3))

print("zeros:", z)
print('ones:', o)

zeros: [[0. 0. 0.]
 [0. 0. 0.]]
ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
# ndim (nechta array borligini)
a = np.array([[1, 2], [3, 4]])
print('ndim:', a.ndim)

ndim: 2


In [12]:
# arange(oxirgi sonni o'zini chiqarmaydi)
a = np.arange(1, 6)
print('arange:', a)

arange: [1 2 3 4 5]


In [ ]:
# sum(), mean() - sonlarni o'rtacha, max(), min

In [14]:
# flatten()
a = np.array([[1, 2], [3, 4]])
print('flatten:', a.flatten())

flatten: [1 2 3 4]


In [16]:
# T - transpose
a = np.array([[1, 2], [3, 4]])
print('flatten:', a.T)

flatten: [[1 3]
 [2 4]]


In [18]:
# dot() @ -- ko'paytirish
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])
print('dot:', a.dot(b))

dot: [[ 4  4]
 [10  8]]


In [19]:
# random.rand() -- random sonlar => 0.0 ~ 1.0 (1.0 excluded)
a = np.random.rand(2, 3)
print('random rand:', a)

random rand: [[0.1717599  0.9091179  0.39544598]
 [0.37109675 0.10558982 0.66858451]]
