In [ ]:
{
"nbformat": 4,
"nbformat_minor": 0,
"metadata": {
"colab": {
"provenance": [],
      "authorship_tag": "ABX9TyM84hWhO2U+RStNk+1DI+Vf",
"include_colab_link": true
},
"kernelspec": {
"name": "python3",
"display_name": "Python 3"
},
"language_info": {
"name": "python"
}
},
"cells": [
{
"cell_type": "markdown",
"metadata": {
"id": "view-in-github",
"colab_type": "text"
},
"source": [
"<a href=\"https://colab.research.google.com/github/mamurov0104-prog/ai_foundation/blob/main/numpy.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
]
},
{
"cell_type": "code",
"execution_count": 1,
"metadata": {
"colab": {
"base_uri": "https://localhost:8080/"
},
"id": "4KDGgMP1mpkK",
"outputId": "46eceb18-6a33-4821-e2a9-6de7e69c5773"
},
"outputs": [
{
"output_type": "stream",
"name": "stdout",
"text": [
"Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)\n"
]
}
],
"source": [
"pip install numpy\n"
]
},
{
"cell_type": "code",
"source": [
        "# dtype()\n",
        "import numpy as np\n",
        "arr1 = np.array([1, 2, 3])\n",
        "print(\"arr1.item:\", arr1.itemsize)\n",
        "print(\"arr1.dtype >\", arr1.dtype, arr1.nbytes, \"\\n\")\n",
        "\n",
        "arr2 = np.array([1, 2, 3], dtype='int32')\n",
        "print(\"arr2.item:\", arr2.itemsize)\n",
        "print(\"arr2.dtype >\", arr2.dtype, arr2.nbytes, \"\\n\")\n",
        "\n",
        "arr3 = np.ones((1000))\n",
        "print(arr3.nbytes)\n",
        "arr4 = np.ones((1000), dtype='int32')\n",
        "print(arr4.nbytes)\n"
],
"metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "k85_dmbunHbG",
        "outputId": "35dd14c7-83ae-4eec-8b5e-2d95b2643030"
      },
      "execution_count": 1,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "arr1.item: 8\n",
            "arr1.dtype > int64 24 \n",
            "\n",
            "arr2.item: 4\n",
            "arr2.dtype > int32 12 \n",
            "\n",
            "8000\n",
            "4000\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# reshape()\n",
        "arr1 = np.array([1, 2, 3, 4, 5, 6])\n",
        "arr2 = arr1.reshape(2, 3)\n",
        "\n",
        "print(\"arr2:\", arr2)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "0Lv9FFfqLzMV",
        "outputId": "f89a1160-15cb-4ec0-a308-40303975b38a"
      },
      "execution_count": 7,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "arr2: [[1 2 3]\n",
            " [4 5 6]]\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# ndim\n",
        "arr = np.array([1, 2, 3, 4, 5, 6])\n",
        "print(arr.ndim)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "EdssVrAUL4yU",
        "outputId": "e6b4b5be-23cf-4ac6-9afe-67f08ba202bd"
      },
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "1\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# arange\n",
        "arr = np.arange(1, 5)\n",
        "print(arr)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "grEAIXTiL-s_",
        "outputId": "026ffecc-3f98-45dd-c531-2c7f3fd58b6b"
      },
      "execution_count": 6,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "[1 2 3 4]\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# sum() mean() max() min()\n",
        "arr = np.array([12, 2, 3, 7, 5, 7])\n",
        "\n",
        "print(\"sum:\", arr.sum())\n",
        "print(\"mean:\", arr.mean())\n",
        "print(\"max:\", arr.max())\n",
        "print(\"min:\", arr.min())"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "5cjPJwZNMESN",
        "outputId": "eebd4fa1-75c9-43e7-d6dd-9e62e3127c78"
},
      "execution_count": null,
      "outputs": []
      "execution_count": 7,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "sum: 36\n",
            "mean: 6.0\n",
            "max: 12\n",
            "min: 2\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# flatten()\n",
        "\n",
        "arr = np.array([[12, 2, 3], [1, 2, 5]])\n",
        "print(\"flatten:\", arr.flatten())"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "GeWD5sT6MGW_",
        "outputId": "bd439788-d6e4-4af5-80da-608e972ee3e3"
      },
      "execution_count": 8,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "flatten: [12  2  3  1  2  5]\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# T - transpose\n",
        "arr1 = np.array([[12, 2, 3, 4], [1, 2, 5, 8]])\n",
        "print(\"arr1.transpose:\\n\", arr1.T, \"\\n\")\n",
        "\n",
        "arr2 = np.array([\n",
        "    [[12, 2, 3, 4], [1, 2, 5, 8]],\n",
        "    [[17, 5, 2, 4], [8, 7, 5, 3]],\n",
        "    [[7, 15, 0, 2], [3, 1, 9, 1]],\n",
        "  ])\n",
        "print(\"arr2.transpose:\\n\", arr2.transpose(1,0,2))"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "0NK7YO_SMMOJ",
        "outputId": "1345f962-58a8-4ba0-e28c-1f31c7f3223a"
      },
      "execution_count": 10,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "arr1.transpose:\n",
            " [[12  1]\n",
            " [ 2  2]\n",
            " [ 3  5]\n",
            " [ 4  8]] \n",
            "\n",
            "arr2.transpose:\n",
            " [[[12  2  3  4]\n",
            "  [17  5  2  4]\n",
            "  [ 7 15  0  2]]\n",
            "\n",
            " [[ 1  2  5  8]\n",
            "  [ 8  7  5  3]\n",
            "  [ 3  1  9  1]]]\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "arr1 = np.array([[1, 2], [3, 4]])\n",
        "arr2 = np.array([[2, 0], [5, 7]])\n",
        "\n",
        "# haqiqiy linier kopaytirish (zamonaviy)\n",
        "multip1 = arr1 @ arr2\n",
        "print(\"multip1:\", multip1, \"\\n\")\n",
        "\n",
        "# dot function\n",
        "multip2 = np.dot(arr1, arr2)\n",
        "print(\"multip2:\", multip2, \"\\n\")\n",
        "\n",
        "# dot method\n",
        "multip3 = arr1.dot(arr2)\n",
        "print(\"multip3:\", multip3, \"\\n\")\n",
        "\n",
        "# Bu esa haqiqiy kopaytirish emas!\n",
        "multip4 = arr1 * arr2\n",
        "print(\"multip4:\", multip4)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "bqwK-dWiMS8s",
        "outputId": "680155d5-9ebb-4639-94f6-17b0ae056e30"
      },
      "execution_count": 11,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "multip1: [[12 14]\n",
            " [26 28]] \n",
            "\n",
            "multip2: [[12 14]\n",
            " [26 28]] \n",
            "\n",
            "multip3: [[12 14]\n",
            " [26 28]] \n",
            "\n",
            "multip4: [[ 2  0]\n",
            " [15 28]]\n"
          ]
        }
      ]
}
]
}